# Generated by Django 5.0.6 on 2024-06-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_inmueble_tipoinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='propiedades.comuna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='propiedades.region'),
        ),
    ]
