# Generated by Django 5.0.6 on 2024-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_comuna_alter_comuna_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
        migrations.DeleteModel(
            name='TipoInmueble',
        ),
    ]
